### ISSUE TITLE
Support for ThemeProvider usage

### ISSUE THREAD

**Issue by Kuboczoch** [dvpnt/styled-media-helper#13]
In `styled-breakpoints` we have an option to use a global theme that can be provided to each component without any import. For now, I can see that we have to use it that way:
```
const media = mediaHelper({
  sm: 320,
  md: 768,
  lg: 1240
});
```
And I have to import it each time I will use it.

There is a way that `styled-media-helper` can support `ThemeProvider`?

**Comment by shtyr-maxim** [comment]
good think

**Comment by shtyr-maxim** [comment]
:thinking: Wait, `styled-breakpoints` requires to write `import { up, only, down, between } from "styled-breakpoints";` in each file where media is used.

So what's the difference between these imports? Using this package you can flexible apply different size hashes in one component like this:
```js
// media.js
import mediaHelper from 'styled-media-helper';

export default mediaHelper({
  sm: 320,
  md: 768,
  lg: 1240
});
```
```js
// anotherMedia.js
import mediaHelper from 'styled-media-helper';

export default mediaHelper({
  sm: 220,
  md: 550,
  lg: 1000
});
```
```js
// component.js
import styled from 'styled-components';
import media from './media';
import anotherMedia from './anotherMedia';

export default styled.div`
	width: 20px;
	color: black;

	${media.between('md', 'lg')} {
		width: 40px;
	}

	${anotherMedia.between('md', 'lg')} {
		color: blue;
	}
`
```
With `ThemeProvider` you can't make it simple

**Comment by shtyr-maxim** [comment]
and now its differences to `styled-breakpoints` https://github.com/dvpnt/styled-media-helper/issues/12

**Comment by Kuboczoch** [comment]
I think the main difference is in there:
```
import media from './media';
```
and
```
import { up, only, down, between } from "styled-breakpoints";
```

Whereas you can see, we are importing each time the same package in `styled-breakpoints` and when we will use `styled-media-helper` we have to import a specific file relative to the file we are using to make it work.
In a far more complex project, it can be difficult to see which one media you are using when you give it a quick look.

For me, the best way to declare sizes is in a `ThemeProvider` when you can declare it globally, which will result in a more readable and clean code.

**Comment by polarathene** [comment]
The multiple breakpoint objects can be a single module and export them, then you'd import similar to `styled-breakpoints` anyway, if you have issue about how you refer to it, you can set an alias with your config like webpack, not really much more magic than a ThemeProvider in another file taking your breakpoints.

```js
import { media, anotherMedia } from "@breakpoints";
```

@shtyr-maxim makes a good point of this difference, as `styled-media-helper` actually supports modularizing your breakpoints, instead of globally scoping them in one object. If you're ok with the global scope grouping or are only in need of a standardized set of breakpoints(eg mobile/tablet/desktop), then that's fine.. but if you want to break based on content for some items but leverage the API + string keys vs raw queries, `styled-media-helper` is more useful here.
